[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "."
  command = "pnpm build"
  publish = "dist"
  # functions = "./functions"